replicaCount: 1

# -- The proxies that are trusted by the importer
trustedProxies: "**"

fireflyiii:
  # -- The URL at which Firefly III is available. If you change this value, click the "Reauthenticate" button on the importer after opening it!
  url: "http://firefly-firefly-iii:80"

  auth:
    # -- If you specify an existingSecret, it has to have the accessToken in a .spec.data.accessToken
    existingSecret: ""

    # -- The access token in plain text
    accessToken: ""

image:
  repository: fireflyiii/data-importer
  pullPolicy: IfNotPresent
  tag: "version-0.8.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
