image:
  repository: postgres
  tag: 10-alpine
  pullPolicy: IfNotPresent

storage:
  class: ~
  accessModes: ReadWriteOnce
  dataSize: 1Gi

configs:
  RESTORE_URL: ""
  BACKUP_URL: ""
  PGPASSWORD: ""
  DBHOST: firefly-firefly-db
  DBPORT: "5432"
  DBNAME: firefly
  DBUSER: firefly
  TZ: Europe/Berlin
  POSTGRES_HOST_AUTH_METHOD: trust
  POSTGRES_USER: firefly
  POSTGRES_PASSWORD: ""

backupSchedule: "0 3 * * *"
