apiVersion: v2
name: firefly-iii-stack
description: Installs Firefly III stack (db, app, importer)
version: 0.4.1
dependencies:
- name: firefly-db
  version: 0.0.4
  condition: firefly-db.enabled
  repository:  "file://../firefly-db"
- name: firefly-iii
  version: 1.0.1
  condition: firefly-iii.enabled
  repository: "file://../firefly-iii"
- name: importer
  version: 1.1.1
  condition: importer.enabled
  repository: "file://../importer"
