apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "firefly-csv.fullname" . }}-pvc
spec:
  {{- with .Values.storage.class }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
    - {{ .Values.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.dataSize }}
