apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "firefly-csv.fullname" . }}-ing
  labels:
    app: {{ template "firefly-csv.name" . }}
    chart: {{ template "firefly-csv.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.hostName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ template "firefly-csv.fullname" . }}-svc
            port:
              number: 8080
