apiVersion: v2
name: firefly
description: Installs Firefly III stack (db, app, importer)
version: 0.0.5
dependencies:
- name: firefly-db
  version: 0.0.3
  condition: firefly-db.enabled
  repository: "file://../firefly-db"
- name: firefly-iii
  version: 0.0.5
  condition: firefly-iii.enabled
  repository: "file://../firefly-iii"
- name: importer
  version: 1.0.0
  condition: importer.enabled
  repository: "file://../importer"
